#include <assert.h>
#include "properties.h"

// This file is autogenerated

bool prop_get_nth_value( prop_t* prop, uint32_t idx, void* out_value ) {
  assert( prop );
  assert( out_value );
  if( idx >= prop->num_enums )
    return false;
  if( prop->data_type == PDT_U16 ) {
    assert( prop->enums_data );
    uint16_t* d = (uint16_t*) prop->enums_data;
    *(uint32_t*) out_value = (uint32_t) d[idx];
    return true;
  }
  if( prop->data_type == PDT_U32 ) {
    assert( prop->enums_data );
    uint32_t* d = (uint32_t*) prop->enums_data;
    *(uint32_t*) out_value = d[idx];
    return true;
  }
  return false;
}

prop_t* prop_by_id( uint16_t prop_id ) {
  switch( prop_id ) {
    case 0xd018: return &prop_quality;
    case 0xd207: return &prop_priority_mode;
    case 0xd208: return &prop_capture_control;
    case 0xd212: return &prop_pending_events;
    case 0x5012: return &prop_pre_capture_delay;
    case 0x500a: return &prop_focus_mode;
    case 0x500f: return &prop_exposure_index;
    case 0x500d: return &prop_exposure_time;
    default: break;
  }
  return 0;
}

const char*   prop_get_value_str( prop_t* p ) {
  switch( p->id ) {

    case 0xd018: {  // quality
      switch( p->ivalue ) {
        case PDV_Quality_Raw                 : return "Raw";
        case PDV_Quality_Fine                : return "Fine";
        case PDV_Quality_Normal              : return "Normal";
        case PDV_Quality_Fine_Raw            : return "Fine Raw";
        case PDV_Quality_Normal_Raw          : return "Normal Raw";
        default: break;
      }
      break;
    }

    case 0xd207: {  // priority_mode
      switch( p->ivalue ) {
        case PDV_Priority_Mode_Camera        : return "Camera";
        case PDV_Priority_Mode_USB           : return "USB";
        default: break;
      }
      break;
    }

    case 0xd208: {  // capture_control
      switch( p->ivalue ) {
        case PDV_Capture_Control_AutoFocus   : return "AutoFocus";
        case PDV_Capture_Control_Shoot       : return "Shoot";
        default: break;
      }
      break;
    }

    case 0x5012: {  // pre_capture_delay
      switch( p->ivalue ) {
        case PDV_Pre_Capture_Delay_Off       : return "Off";
        case PDV_Pre_Capture_Delay_2_Secs    : return "2 Secs";
        case PDV_Pre_Capture_Delay_10_Secs   : return "10 Secs";
        default: break;
      }
      break;
    }

    case 0x500a: {  // focus_mode
      switch( p->ivalue ) {
        case PDV_Focus_Mode_Manual           : return "Manual";
        case PDV_Focus_Mode_Single_Auto      : return "Single Auto";
        case PDV_Focus_Mode_Continuous_Auto  : return "Continuous Auto";
        default: break;
      }
      break;
    }

    case 0x500f: {  // exposure_index
      switch( p->ivalue ) {
        case PDV_Exposure_Index_ISO_100      : return "ISO 100";
        case PDV_Exposure_Index_ISO_200      : return "ISO 200";
        case PDV_Exposure_Index_ISO_800      : return "ISO 800";
        case PDV_Exposure_Index_ISO_1000     : return "ISO 1000";
        case PDV_Exposure_Index_ISO_1250     : return "ISO 1250";
        case PDV_Exposure_Index_ISO_1600     : return "ISO 1600";
        case PDV_Exposure_Index_ISO_2000     : return "ISO 2000";
        case PDV_Exposure_Index_ISO_3200     : return "ISO 3200";
        case PDV_Exposure_Index_ISO_6400     : return "ISO 6400";
        case PDV_Exposure_Index_ISO_12800    : return "ISO 12800";
        case PDV_Exposure_Index_ISO_25600    : return "ISO 25600";
        case PDV_Exposure_Index_ISO_Auto     : return "ISO Auto";
        default: break;
      }
      break;
    }

    case 0x500d: {  // exposure_time
      switch( p->ivalue ) {
        case PDV_Exposure_Time_1_8000_sec    : return "1/8000 sec";
        case PDV_Exposure_Time_1_6400_sec    : return "1/6400 sec";
        case PDV_Exposure_Time_1_5000_sec    : return "1/5000 sec";
        case PDV_Exposure_Time_1_4000_sec    : return "1/4000 sec";
        case PDV_Exposure_Time_1_3200_sec    : return "1/3200 sec";
        case PDV_Exposure_Time_1_2500_sec    : return "1/2500 sec";
        case PDV_Exposure_Time_1_1600_sec    : return "1/1600 sec";
        case PDV_Exposure_Time_1_1250_sec    : return "1/1250 sec";
        case PDV_Exposure_Time_1_1000_sec    : return "1/1000 sec";
        case PDV_Exposure_Time_1_800_sec     : return "1/800 sec";
        case PDV_Exposure_Time_1_640_sec     : return "1/640 sec";
        case PDV_Exposure_Time_1_500_sec     : return "1/500 sec";
        case PDV_Exposure_Time_1_400_sec     : return "1/400 sec";
        case PDV_Exposure_Time_1_320_sec     : return "1/320 sec";
        case PDV_Exposure_Time_1_250_sec     : return "1/250 sec";
        case PDV_Exposure_Time_1_200_sec     : return "1/200 sec";
        case PDV_Exposure_Time_1_160_sec     : return "1/160 sec";
        case PDV_Exposure_Time_1_125_sec     : return "1/125 sec";
        case PDV_Exposure_Time_1_100_sec     : return "1/100 sec";
        case PDV_Exposure_Time_1_80_sec      : return "1/80 sec";
        case PDV_Exposure_Time_1_60_sec      : return "1/60 sec";
        case PDV_Exposure_Time_1_50_sec      : return "1/50 sec";
        case PDV_Exposure_Time_1_40_sec      : return "1/40 sec";
        case PDV_Exposure_Time_1_30_sec      : return "1/30 sec";
        case PDV_Exposure_Time_1_25_sec      : return "1/25 sec";
        case PDV_Exposure_Time_1_20_sec      : return "1/20 sec";
        case PDV_Exposure_Time_1_15_sec      : return "1/15 sec";
        case PDV_Exposure_Time_1_13_sec      : return "1/13 sec";
        case PDV_Exposure_Time_1_10_sec      : return "1/10 sec";
        case PDV_Exposure_Time_1_8_sec       : return "1/8 sec";
        case PDV_Exposure_Time_1_6_sec       : return "1/6 sec";
        case PDV_Exposure_Time_1_5_sec       : return "1/5 sec";
        case PDV_Exposure_Time_1_4_sec       : return "1/4 sec";
        case PDV_Exposure_Time_1_3_sec       : return "1/3 sec";
        case PDV_Exposure_Time_1_2_sec       : return "1/2 sec";
        case PDV_Exposure_Time_1_sec         : return "1 sec";
        case PDV_Exposure_Time_1_3_secs      : return "1.3 secs";
        case PDV_Exposure_Time_1_5_secs      : return "1.5 secs";
        case PDV_Exposure_Time_2_secs        : return "2 secs";
        case PDV_Exposure_Time_2_5_secs      : return "2.5 secs";
        case PDV_Exposure_Time_3_secs        : return "3 secs";
        case PDV_Exposure_Time_4_secs        : return "4 secs";
        case PDV_Exposure_Time_5_secs        : return "5 secs";
        case PDV_Exposure_Time_6_5_secs      : return "6.5 secs";
        case PDV_Exposure_Time_8_secs        : return "8 secs";
        case PDV_Exposure_Time_10_secs       : return "10 secs";
        case PDV_Exposure_Time_13_secs       : return "13 secs";
        case PDV_Exposure_Time_15_secs       : return "15 secs";
        case PDV_Exposure_Time_20_secs       : return "20 secs";
        case PDV_Exposure_Time_25_secs       : return "25 secs";
        case PDV_Exposure_Time_30_secs       : return "30 secs";
        case PDV_Exposure_Time_40_secs       : return "40 secs";
        case PDV_Exposure_Time_50_secs       : return "50 secs";
        case PDV_Exposure_Time_60_secs       : return "60 secs";
        case PDV_Exposure_Time_2_mins        : return "2 mins";
        case PDV_Exposure_Time_4_mins        : return "4 mins";
        case PDV_Exposure_Time_8_mins        : return "8 mins";
        case PDV_Exposure_Time_15_mins       : return "15 mins";
        default: break;
      }
      break;
    }

    default: break;
  }
  return "Unknown";
}

const uint16_t prop_quality_values[] = { 0x0001, 0x0002, 0x0003, 0x0004, 0x0005};
prop_t prop_quality = { .id = 0xd018, .name = "Quality", .data_type = PDT_U16,
                        .read_only = false, .ivalue = 0, 
                        .blob = { .count = 0, .data = 0, .reserved = 0 }, 
                        .num_enums = 5, .enums_data = &prop_quality_values };
const uint16_t prop_priority_mode_values[] = { 0x0001, 0x0002};
prop_t prop_priority_mode = { .id = 0xd207, .name = "Priority Mode", .data_type = PDT_U16,
                        .read_only = false, .ivalue = 0, 
                        .blob = { .count = 0, .data = 0, .reserved = 0 }, 
                        .num_enums = 2, .enums_data = &prop_priority_mode_values };
const uint16_t prop_capture_control_values[] = { 0x0200, 0x0304};
prop_t prop_capture_control = { .id = 0xd208, .name = "Capture Control", .data_type = PDT_U16,
                        .read_only = false, .ivalue = 0, 
                        .blob = { .count = 0, .data = 0, .reserved = 0 }, 
                        .num_enums = 2, .enums_data = &prop_capture_control_values };
prop_t prop_pending_events = { .id = 0xd212, .name = "Pending Events", .data_type = PDT_ARRAY_PROP_VALUES,
                        .read_only = true, .ivalue = 0, 
                        .blob = { .count = 0, .data = 0, .reserved = 0 }, 
                        .num_enums = 0, .enums_data = 0 };
const uint16_t prop_pre_capture_delay_values[] = { 0x0000, 0x07d0, 0x2710};
prop_t prop_pre_capture_delay = { .id = 0x5012, .name = "Pre Capture Delay", .data_type = PDT_U16,
                        .read_only = false, .ivalue = 0, 
                        .blob = { .count = 0, .data = 0, .reserved = 0 }, 
                        .num_enums = 3, .enums_data = &prop_pre_capture_delay_values };
const uint16_t prop_focus_mode_values[] = { 0x0001, 0x8001, 0x8002};
prop_t prop_focus_mode = { .id = 0x500a, .name = "Focus Mode", .data_type = PDT_U16,
                        .read_only = false, .ivalue = 0, 
                        .blob = { .count = 0, .data = 0, .reserved = 0 }, 
                        .num_enums = 3, .enums_data = &prop_focus_mode_values };
const uint32_t prop_exposure_index_values[] = { 0x00000064, 0x000000c8, 0x00000320, 0x000003e8, 0x000004e2, 0x00000640, 0x000007D0, 0x00000c80, 0x00001900, 0x00003200, 0x00006400, 0xffffffff};
prop_t prop_exposure_index = { .id = 0x500f, .name = "Exposure Index", .data_type = PDT_U32,
                        .read_only = false, .ivalue = 0, 
                        .blob = { .count = 0, .data = 0, .reserved = 0 }, 
                        .num_enums = 12, .enums_data = &prop_exposure_index_values };
const uint32_t prop_exposure_time_values[] = { 0x0000007a, 0x00000099, 0x000000c1, 0x000000f4, 0x00000133, 0x00000183, 0x00000267, 0x00000307, 0x000003d0, 0x000004ce, 0x0000060e, 0x000007a1, 0x0000099c, 0x00000c1c, 0x00000f42, 0x00001339, 0x00001838, 0x00001e84, 0x00002673, 0x00003071, 0x00003d09, 0x00004ce6, 0x000060e3, 0x00007a12, 0x000099cc, 0x0000c1c6, 0x0000f424, 0x00013399, 0x0001838c, 0x0001e848, 0x00026732, 0x00030719, 0x0003d090, 0x0004ce64, 0x0007a120, 0x000f4240, 0x00133991, 0x001836c9, 0x001e8480, 0x00267522, 0x00307192, 0x003d0900, 0x004ce644, 0x0060e324, 0x007a1200, 0x0099cc88, 0x00c1c648, 0x00f42400, 0x01339910, 0x01838c90, 0x01e84800, 0x02673221, 0x03071921, 0x03d09000, 0x03d0901e, 0x03d0903c, 0x03d0905a, 0x03d09078};
prop_t prop_exposure_time = { .id = 0x500d, .name = "Exposure Time", .data_type = PDT_U32,
                        .read_only = false, .ivalue = 0, 
                        .blob = { .count = 0, .data = 0, .reserved = 0 }, 
                        .num_enums = 58, .enums_data = &prop_exposure_time_values };


const prop_t* props[] = {
  &prop_quality,
  &prop_priority_mode,
  &prop_capture_control,
  &prop_pending_events,
  &prop_pre_capture_delay,
  &prop_focus_mode,
  &prop_exposure_index,
  &prop_exposure_time,
  0L   // End of array
};

const prop_t** prop_get_all( ) { return props; }