#include "properties.h"

// This file is autogenerated

const char* prop_get_value_str( prop_t* p ) {
  switch( p->id ) {

    case 0xd018: {  // quality
      switch( p->ivalue ) {
        case 0x0001: return "Raw";
        case 0x0002: return "Fine";
        case 0x0003: return "Normal";
        case 0x0004: return "Fine Raw";
        case 0x0005: return "Normal Raw";
        default: break;
      }
      break;
    }

    case 0xd207: {  // priority_mode
      switch( p->ivalue ) {
        case 0x0001: return "Camera";
        case 0x0002: return "USB";
        default: break;
      }
      break;
    }

    case 0xd208: {  // capture_control
      switch( p->ivalue ) {
        case 0x0200: return "AutoFocus";
        case 0x0304: return "Shoot";
        default: break;
      }
      break;
    }

    default: break;
  }
  return "Unknown";
}

const prop_t prop_quality = { .id = 0xd018, .name = "Quality", .data_type = PDT_U16, .ivalue = 0 };
const prop_t prop_priority_mode = { .id = 0xd207, .name = "Priority Mode", .data_type = PDT_U16, .ivalue = 0 };
const prop_t prop_capture_control = { .id = 0xd208, .name = "Capture Control", .data_type = PDT_U16, .ivalue = 0 };
const prop_t prop_pending_events = { .id = 0xd212, .name = "Pending Events", .data_type = PDT_ARRAY_PROP_VALUES, .ivalue = 0 };

